version: '3'

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - ./data:/var/lib/postgresql/data

  odoo:
    image: odoo-debug
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "5678:5678"  # Port for remote debugging
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf  # Mount the local odoo.conf file
      - ./custom_addons:/mnt/extra-addons  # Mount your custom addons
      - ./odoo-14.0:/usr/lib/python3/dist-packages/odoo  # Mount Odoo source code
      - ./filestore:/var/lib/odoo
    command: >
      bash -c "python3 -m debugpy --listen 0.0.0.0:5678 --wait-for-client /usr/lib/python3/dist-packages/odoo/odoo-bin -c /etc/odoo/odoo.conf --dev xml"
